import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Navbar from './components/Navbar/navbar'
import ClientOnly from './components/ClientOnly'

import RegisterModal from './components/Modals/RegisterModal'
const font = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AirBnb',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly >
          <RegisterModal />
        <Navbar />
        </ClientOnly>
       
        {children}
        </body>
    </html>
  )
}
